version: "3"

services:
  temp_sensor:
    image: antonaleks/data-simulator
    environment:
      - SIM_HOST=192.168.1.1
      - SIM_NAME=TIRCAHL24
      - SIM_PERIOD=5
      - SIM_TYPE=temperature
  pressure_sensor:
    image: antonaleks/data-simulator
    environment:
      - SIM_HOST=192.168.1.1
        - SIM_NAME=PIRCAHL11
        - SIM_PERIOD=10
        - SIM_TYPE=pressure
  current_sensor:
    image: antonaleks/data-simulator
    environment:
      - SIM_HOST=192.168.1.1
        - SIM_NAME=A0_CURRENT
        - SIM_PERIOD=1
        - SIM_TYPE=current